import type { ProviderPreset } from "../types";

/**
 * Curated shortcuts for providers that can be represented directly by Droid's
 * BYOK schema. Model catalogs change frequently, so rolling/preview entries are
 * labelled and the custom form remains the source of truth for other models.
 */
export const providerPresets: ProviderPreset[] = [
  {
    id: "anthropic",
    name: "Anthropic",
    icon: "anthropic",
    category: "official",
    model: "claude-sonnet-4-6",
    baseUrl: "https://api.anthropic.com",
    provider: "anthropic",
    description: "Anthropic 官方 Messages API",
    protocolNote: "Droid provider=anthropic；Base URL 使用官方根地址，Droid 调用 /v1/messages。",
    endpointNote: "https://api.anthropic.com → /v1/messages",
    verificationNote: "协议、Endpoint 与当前列出的精确模型已按 Factory BYOK / Anthropic 官方模型页核对（2026-06-28）；可用目录仍可能更新。",
    verificationStatus: "verified",
    maxOutputVerificationNote: "当前精确模型按 Anthropic 同步 Messages API 上限自动填充；Batch 300K beta 不作为普通请求上限写入。",
    contextWindowVerificationNote: "精确模型按 Anthropic 当前模型页核验；不同云平台可能存在单独限制。",
    billingNote: "按输入 / 缓存写入 / 缓存读取 / 输出 Token 分别计费；Batch、Fast mode、区域处理可能使用不同费率。",
    protocols: [
      {
        provider: "anthropic",
        baseUrl: "https://api.anthropic.com",
        status: "recommended",
        endpointNote: "https://api.anthropic.com → /v1/messages",
        note: "Factory BYOK 官方示例使用 provider=anthropic。",
      },
    ],
    referenceUrl: "https://docs.factory.ai/cli/byok/openai-anthropic",
    websiteUrl: "https://console.anthropic.com",
    apiKeyUrl: "https://console.anthropic.com/settings/keys",
    models: [
      { model: "claude-opus-4-8", displayName: "Claude Opus 4.8", contextWindow: 1000000, contextWindowVerified: true, maxOutputTokens: 128000, maxOutputVerified: true, stability: "stable" },
      { model: "claude-opus-4-7", displayName: "Claude Opus 4.7", contextWindow: 1000000, contextWindowVerified: true, maxOutputTokens: 128000, maxOutputVerified: true, stability: "stable" },
      { model: "claude-sonnet-4-6", displayName: "Claude Sonnet 4.6", contextWindow: 1000000, contextWindowVerified: true, maxOutputTokens: 128000, maxOutputVerified: true, stability: "stable" },
      { model: "claude-haiku-4-5-20251001", displayName: "Claude Haiku 4.5", contextWindow: 200000, contextWindowVerified: true, maxOutputTokens: 64000, maxOutputVerified: true, stability: "stable" },
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    icon: "openai",
    category: "official",
    model: "gpt-5.5",
    baseUrl: "https://api.openai.com/v1",
    provider: "openai",
    description: "OpenAI 官方 Responses API",
    protocolNote: "Droid provider=openai；使用 Responses API。",
    endpointNote: "https://api.openai.com/v1 → /responses",
    verificationNote: "协议、Endpoint 与 GPT-5.5 / GPT-5.4 已按 Factory BYOK、OpenAI 模型页和 Compare 页核对（2026-06-28）。",
    verificationStatus: "verified",
    maxOutputVerificationNote: "GPT-5.5 / GPT-5.4 的 128,000 输出上限已交叉核验；未核验型号保持为空。",
    contextWindowVerificationNote: "GPT-5.5 / GPT-5.4 按 OpenAI 官方模型页与 Compare 页交叉核验。",
    billingNote: "按输入、缓存输入和输出 Token 分别计费；长输入、Batch、Flex、Priority 与区域处理可能使用不同费率。",
    protocols: [
      {
        provider: "openai",
        baseUrl: "https://api.openai.com/v1",
        status: "recommended",
        endpointNote: "https://api.openai.com/v1 → /responses",
        note: "Factory BYOK 官方示例使用 provider=openai。",
      },
    ],
    referenceUrl: "https://docs.factory.ai/cli/byok/openai-anthropic",
    websiteUrl: "https://platform.openai.com",
    apiKeyUrl: "https://platform.openai.com/api-keys",
    models: [
      { model: "gpt-5.5", displayName: "GPT-5.5", contextWindow: 1050000, contextWindowVerified: true, maxOutputTokens: 128000, maxOutputVerified: true, stability: "stable" },
      { model: "gpt-5.4", displayName: "GPT-5.4", contextWindow: 1050000, contextWindowVerified: true, maxOutputTokens: 128000, maxOutputVerified: true, stability: "stable" },
      { model: "gpt-5.4-mini", displayName: "GPT-5.4 Mini", stability: "rolling" },
    ],
  },
  {
    id: "gemini",
    name: "Google Gemini",
    icon: "gemini",
    category: "official",
    model: "gemini-3.5-flash",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai/",
    provider: "generic-chat-completion-api",
    description: "Google 官方 OpenAI-compatible endpoint",
    protocolNote: "Droid provider=generic-chat-completion-api；调用 Chat Completions 兼容接口。",
    endpointNote: "https://generativelanguage.googleapis.com/v1beta/openai/ → /chat/completions",
    verificationNote: "Gemini OpenAI compatibility endpoint 与 3.5 Flash 参数已按 Google/Factory 文档核对。",
    verificationStatus: "verified",
    maxOutputVerificationNote: "Gemini 3.5 Flash 的 65,536 输出上限已按 Google 模型页与 Factory Gemini BYOK 入口核对；Preview 型号不自动写入。",
    contextWindowVerificationNote: "Gemini 3.5 Flash 的 1,048,576 输入上限已按 Google 精确模型页核对。",
    billingNote: "按输入与输出 Token 分别计费；Batch、Flex、Priority 等消费方式可能使用不同费率。",
    protocols: [
      {
        provider: "generic-chat-completion-api",
        baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai/",
        status: "recommended",
        endpointNote: "https://generativelanguage.googleapis.com/v1beta/openai/ → /chat/completions",
        note: "Google OpenAI compatibility endpoint；Droid generic provider 会调用 Chat Completions。",
      },
    ],
    referenceUrl: "https://docs.factory.ai/cli/byok/google-gemini",
    websiteUrl: "https://ai.google.dev",
    apiKeyUrl: "https://aistudio.google.com/apikey",
    models: [
      { model: "gemini-3.5-flash", displayName: "Gemini 3.5 Flash", maxOutputTokens: 65536, maxOutputVerified: true, contextWindow: 1048576, contextWindowVerified: true, stability: "stable" },
      { model: "gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro Preview", stability: "preview" },
    ],
  },
  {
    id: "zhipu",
    name: "智谱 GLM",
    icon: "zhipu",
    category: "official",
    model: "glm-5.2",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    provider: "generic-chat-completion-api",
    noImageSupport: true,
    description: "智谱 BigModel 官方 OpenAI-compatible API",
    protocolNote: "Droid provider=generic-chat-completion-api；调用 Chat Completions 兼容接口。",
    endpointNote: "https://open.bigmodel.cn/api/paas/v4 → /chat/completions",
    verificationNote: "GLM-5.2/GLM-5.1/GLM-5 的 context 与输出上限按智谱模型概览核对。",
    verificationStatus: "verified",
    maxOutputVerificationNote: "GLM-5.2/GLM-5.1/GLM-5 的 128K 输出上限已按智谱官方模型概览核对。",
    contextWindowVerificationNote: "GLM-5.2 为 1M；GLM-5.1/GLM-5 为 200K，按智谱官方模型概览核对。",
    billingNote: "按量 API；输入与输出 Token 费率以 BigModel 当前价格页和账户区域为准。",
    protocols: [
      {
        provider: "generic-chat-completion-api",
        baseUrl: "https://open.bigmodel.cn/api/paas/v4",
        status: "recommended",
        endpointNote: "https://open.bigmodel.cn/api/paas/v4 → /chat/completions",
        note: "智谱 API 文档为 OpenAI-compatible Chat Completions 风格。",
      },
    ],
    referenceUrl: "https://docs.bigmodel.cn/cn/guide/start/model-overview",
    websiteUrl: "https://open.bigmodel.cn",
    apiKeyUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    models: [
      { model: "glm-5.2", displayName: "GLM-5.2", maxOutputTokens: 131072, maxOutputVerified: true, contextWindow: 1048576, contextWindowVerified: true, stability: "stable" },
      { model: "glm-5.1", displayName: "GLM-5.1", maxOutputTokens: 131072, maxOutputVerified: true, contextWindow: 204800, contextWindowVerified: true, stability: "stable" },
      { model: "glm-5", displayName: "GLM-5", maxOutputTokens: 131072, maxOutputVerified: true, contextWindow: 204800, contextWindowVerified: true, stability: "stable" },
    ],
  },
  {
    id: "zai-coding-plan",
    name: "Z.AI GLM Coding Plan",
    icon: "zhipu",
    category: "plan",
    model: "GLM-5.2",
    baseUrl: "https://api.z.ai/api/anthropic",
    provider: "anthropic",
    noImageSupport: true,
    description: "Z.AI GLM Coding Plan 专属 Endpoint；与通用按量 API 分开",
    protocolNote: "Coding Plan 官方提供 Anthropic Messages 与 OpenAI Chat Completions 两种协议。",
    endpointNote: "https://api.z.ai/api/anthropic → /v1/messages",
    verificationNote: "Coding Plan 专属 Endpoint 已按 Z.AI Quick Start / Tool Integration 核对；支持模型目录会滚动更新。",
    verificationStatus: "verified",
    maxOutputVerificationNote: "GLM-5.2 精确模型 128K 最大输出按 Z.AI / GLM 官方资料交叉核验。",
    contextWindowVerificationNote: "GLM-5.2 精确模型 1M context 按 Z.AI / GLM 官方资料交叉核验。",
    billingNote: "订阅计划额度；不同模型可能按倍率扣减。必须使用 Coding Plan Key 和专属 Endpoint。",
    protocols: [
      {
        id: "zai-coding-anthropic",
        provider: "anthropic",
        baseUrl: "https://api.z.ai/api/anthropic",
        status: "recommended",
        label: "Anthropic Messages",
        serviceLabel: "Z.AI GLM Coding Plan",
        endpointNote: "https://api.z.ai/api/anthropic → /v1/messages",
        note: "Claude Code 风格工具的官方 Coding Plan Endpoint。",
        billingNote: "订阅计划额度；不要换成通用 `/api/paas/v4` Endpoint。",
        referenceUrl: "https://docs.z.ai/devpack/quick-start",
      },
      {
        id: "zai-coding-openai-chat",
        provider: "generic-chat-completion-api",
        baseUrl: "https://api.z.ai/api/coding/paas/v4",
        status: "available",
        label: "OpenAI Chat Completions",
        serviceLabel: "Z.AI GLM Coding Plan",
        endpointNote: "https://api.z.ai/api/coding/paas/v4 → /chat/completions",
        note: "其他 OpenAI-compatible 编程工具的官方 Coding Plan Endpoint。",
        billingNote: "订阅计划额度；不要换成通用 `/api/paas/v4` Endpoint。",
        referenceUrl: "https://docs.z.ai/devpack/tool/others",
      },
    ],
    referenceUrl: "https://docs.z.ai/devpack/quick-start",
    websiteUrl: "https://z.ai/subscribe",
    apiKeyUrl: "https://z.ai/manage-apikey/apikey-list",
    models: [
      { model: "GLM-5.2", displayName: "GLM-5.2", maxOutputTokens: 131072, maxOutputVerified: true, contextWindow: 1048576, contextWindowVerified: true, stability: "stable" },
      { model: "GLM-5.1", displayName: "GLM-5.1", maxOutputTokens: 131072, maxOutputVerified: true, contextWindow: 204800, contextWindowVerified: true, stability: "stable" },
    ],
  },
  {
    id: "minimax",
    name: "MiniMax Token Plan",
    icon: "minimax",
    category: "plan",
    model: "MiniMax-M3",
    baseUrl: "https://api.minimax.io/anthropic",
    provider: "anthropic",
    description: "MiniMax Token Plan；按服务域名自动关联 Anthropic / OpenAI-compatible Endpoint",
    protocolNote: "MiniMax Token Plan 官方提供 Anthropic-compatible 与 OpenAI-compatible 两种协议，并区分 minimax.io / minimaxi.com 服务域名。",
    endpointNote: "https://api.minimax.io/anthropic → /v1/messages",
    verificationNote: "MiniMax Token Plan 当前快速接入示例使用 MiniMax-M3 与 Anthropic-compatible endpoint；maxOutputTokens 未在本预设强制写入，用户已有配置会保留。",
    verificationStatus: "verified",
    maxOutputVerificationNote: "MiniMax Token Plan 文档未给出可稳定写入本预设的统一最大输出值，因此不自动填 maxOutputTokens。",
    contextWindowVerificationNote: "MiniMax M3 Token Plan 当前订阅页标注 1M context；M2.7 保留历史兼容但不自动写入上下文。",
    billingNote: "Token Plan / Credits 额度；不同模型可能按 Token、请求窗口或日配额扣减，Key 与按量 API Key 不互通。",
    protocols: [
      {
        id: "minimax-global-anthropic",
        provider: "anthropic",
        baseUrl: "https://api.minimax.io/anthropic",
        status: "recommended",
        label: "Anthropic Messages",
        serviceLabel: "MiniMax · minimax.io",
        endpointNote: "https://api.minimax.io/anthropic → /v1/messages",
        note: "官方说明 Anthropic-compatible 对 Claude Code 风格工具更合适，并支持 prompt cache。",
        billingNote: "Token Plan / Credits 专用 Key；额度规则按当前模型和计划扣减。",
        referenceUrl: "https://platform.minimax.io/docs/token-plan/other-tools",
      },
      {
        id: "minimax-global-openai-chat",
        provider: "generic-chat-completion-api",
        baseUrl: "https://api.minimax.io/v1",
        status: "available",
        label: "OpenAI Chat Completions",
        serviceLabel: "MiniMax · minimax.io",
        endpointNote: "https://api.minimax.io/v1 → /chat/completions",
        note: "官方 OpenAI-compatible 入口；Droid 使用 generic-chat-completion-api。",
        billingNote: "Token Plan / Credits 专用 Key；额度规则按当前模型和计划扣减。",
        referenceUrl: "https://platform.minimax.io/docs/token-plan/other-tools",
      },
      {
        id: "minimax-minimaxi-anthropic",
        provider: "anthropic",
        baseUrl: "https://api.minimaxi.com/anthropic",
        status: "recommended",
        label: "Anthropic Messages",
        serviceLabel: "MiniMax · minimaxi.com",
        endpointNote: "https://api.minimaxi.com/anthropic → /v1/messages",
        note: "minimaxi.com 服务的 Token Plan Anthropic-compatible 入口。",
        billingNote: "Token Plan / Credits 专用 Key；与按量 API Key 不互通。",
        referenceUrl: "https://platform.minimaxi.com/docs/coding-plan/grok-cli",
      },
      {
        id: "minimax-minimaxi-openai-chat",
        provider: "generic-chat-completion-api",
        baseUrl: "https://api.minimaxi.com/v1",
        status: "available",
        label: "OpenAI Chat Completions",
        serviceLabel: "MiniMax · minimaxi.com",
        endpointNote: "https://api.minimaxi.com/v1 → /chat/completions",
        note: "minimaxi.com 服务的 Token Plan OpenAI-compatible 入口。",
        billingNote: "Token Plan / Credits 专用 Key；与按量 API Key 不互通。",
        referenceUrl: "https://platform.minimaxi.com/docs/coding-plan/grok-cli",
      },
    ],
    referenceUrl: "https://platform.minimaxi.com/docs/token-plan/intro",
    websiteUrl: "https://platform.minimaxi.com/docs/token-plan/intro",
    apiKeyUrl: "https://platform.minimaxi.com/user-center/basic-information/interface-key",
    models: [
      { model: "MiniMax-M3", displayName: "MiniMax M3", contextWindow: 1000000, contextWindowVerified: true, stability: "stable" },
      { model: "MiniMax-M2.7", displayName: "MiniMax M2.7（历史兼容）", contextWindow: 204800, stability: "legacy" },
    ],
  },
  {
    id: "volcano",
    name: "Volcengine Ark Coding Plan",
    icon: "volcano",
    category: "plan",
    model: "ark-code-latest",
    baseUrl: "https://ark.cn-beijing.volces.com/api/coding",
    provider: "anthropic",
    description: "Volcengine Ark Coding Plan 官方兼容 API",
    protocolNote: "火山方舟 Coding/Agent Plan 官方资料包含 Anthropic-compatible 与 OpenAI-compatible 两类入口；本预设默认使用 Anthropic-compatible。",
    endpointNote: "https://ark.cn-beijing.volces.com/api/coding → /v1/messages",
    verificationNote: "endpoint 与 ark-code-latest 按火山方舟 2026-06 Coding Plan 官方资料核对，rolling 型号不写死输出上限。",
    verificationStatus: "verified",
    maxOutputVerificationNote: "ark-code-latest 为 rolling 型号，不自动写死最大输出。",
    contextWindowVerificationNote: "ark-code-latest 可在控制台切换模型，Context 随实际路由变化，不自动写死。",
    billingNote: "Coding Plan 订阅额度；必须使用计划专属 Key 与 `/api/coding` Endpoint，普通 `/api/v3` 可能产生额外按量费用。",
    protocols: [
      {
        provider: "anthropic",
        baseUrl: "https://ark.cn-beijing.volces.com/api/coding",
        status: "recommended",
        label: "Anthropic Messages",
        serviceLabel: "Volcengine Ark Coding Plan",
        endpointNote: "https://ark.cn-beijing.volces.com/api/coding → /v1/messages",
        note: "默认用于 Claude Code / Anthropic-compatible 工具链。",
        billingNote: "Coding Plan 订阅额度；Endpoint 与计划 Key 必须匹配。",
      },
      {
        provider: "openai",
        baseUrl: "https://ark.cn-beijing.volces.com/api/coding/v3",
        status: "available",
        label: "OpenAI Responses",
        serviceLabel: "Volcengine Ark Coding Plan",
        endpointNote: "https://ark.cn-beijing.volces.com/api/coding/v3 → /responses",
        note: "官方资料同时给出 OpenAI-compatible / Responses 风格入口；用于支持 Responses 的工具链。",
        billingNote: "Coding Plan 订阅额度；Endpoint 与计划 Key 必须匹配。",
      },
      {
        id: "volcengine-openai-chat",
        provider: "generic-chat-completion-api",
        baseUrl: "https://ark.cn-beijing.volces.com/api/coding/v3",
        status: "available",
        label: "OpenAI Chat Completions",
        serviceLabel: "Volcengine Ark Coding Plan",
        endpointNote: "https://ark.cn-beijing.volces.com/api/coding/v3 → /chat/completions",
        note: "官方 OpenAI-compatible 工具示例使用 Chat Completions；Droid 映射 generic-chat-completion-api。",
        billingNote: "Coding Plan 订阅额度；Endpoint 与计划 Key 必须匹配。",
      },
    ],
    referenceUrl: "https://www.volcengine.com/docs/82379/1928261",
    websiteUrl: "https://www.volcengine.com/docs/82379/1928261",
    apiKeyUrl: "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
    models: [
      { model: "ark-code-latest", displayName: "Ark Code Latest", stability: "rolling" },
    ],
  },
  {
    id: "kimi-code",
    name: "Kimi Code",
    icon: "kimi",
    category: "plan",
    model: "kimi-for-coding",
    baseUrl: "https://api.kimi.com/coding/v1",
    provider: "generic-chat-completion-api",
    noImageSupport: true,
    description: "Kimi Code 官方 OpenAI-compatible endpoint（与 Moonshot 开放平台分开）",
    protocolNote: "Kimi Code 官方明确兼容 OpenAI 与 Anthropic 两种协议；本预设默认使用 OpenAI-compatible Chat Completions。",
    endpointNote: "https://api.kimi.com/coding/v1 → /chat/completions",
    verificationNote: "kimi-for-coding、双协议 Base URL 按 Kimi Code 官方文档核对；该稳定 ID 后端会滚动升级，maxOutputTokens 不强制写入。",
    verificationStatus: "verified",
    maxOutputVerificationNote: "Kimi Code 官方文档未要求写固定 maxOutputTokens；本预设保留为空。",
    contextWindowVerificationNote: "kimi-for-coding 是滚动 ID，后端模型会升级；不把某一代模型的 Context 固定写入 settings。",
    billingNote: "Kimi 会员订阅额度，包含滚动时间窗口；与 Kimi Open Platform 按量 API 的 Key / Base URL 不互通。",
    protocols: [
      {
        provider: "generic-chat-completion-api",
        baseUrl: "https://api.kimi.com/coding/v1",
        status: "available",
        label: "OpenAI Chat Completions",
        serviceLabel: "Kimi Code Membership",
        endpointNote: "https://api.kimi.com/coding/v1 → /chat/completions",
        note: "Kimi Code 官方 OpenAI Compatible Base URL。",
        billingNote: "会员订阅额度；API Key 来自 Kimi Code Console。",
      },
      {
        provider: "anthropic",
        baseUrl: "https://api.kimi.com/coding",
        status: "available",
        label: "Anthropic Messages",
        serviceLabel: "Kimi Code Membership",
        endpointNote: "https://api.kimi.com/coding → /v1/messages",
        note: "Kimi Code 官方 Anthropic Compatible Base URL；Droid 会追加 /v1/messages。",
        billingNote: "会员订阅额度；API Key 来自 Kimi Code Console。",
      },
    ],
    referenceUrl: "https://www.kimi.com/code/docs/en/",
    websiteUrl: "https://www.kimi.com/code/docs/en/",
    apiKeyUrl: "https://www.kimi.com/code/console",
    models: [
      { model: "kimi-for-coding", displayName: "Kimi for Coding", stability: "rolling" },
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    icon: "deepseek",
    category: "official",
    model: "deepseek-v4-pro",
    baseUrl: "https://api.deepseek.com",
    provider: "generic-chat-completion-api",
    noImageSupport: true,
    description: "DeepSeek 官方 OpenAI-compatible API；也提供 Anthropic API 格式",
    protocolNote: "DeepSeek 官方同时提供 OpenAI Format 与 Anthropic Format；本预设默认使用 OpenAI-compatible Chat Completions。",
    endpointNote: "https://api.deepseek.com → /chat/completions",
    verificationNote: "模型名、1M context 与 384K 输出上限按 DeepSeek 官方模型/价格页核对。",
    verificationStatus: "verified",
    maxOutputVerificationNote: "DeepSeek V4 Pro/Flash 的 384K 输出上限已按 DeepSeek 官方模型/价格页核对。",
    contextWindowVerificationNote: "DeepSeek V4 Pro/Flash 的 1,000,000 context 已按官方模型页与 Agent 集成示例交叉核对。",
    billingNote: "按输入缓存命中、输入缓存未命中和输出 Token 分别计费。",
    protocols: [
      {
        provider: "generic-chat-completion-api",
        baseUrl: "https://api.deepseek.com",
        status: "available",
        label: "OpenAI Chat Completions",
        serviceLabel: "DeepSeek API",
        endpointNote: "https://api.deepseek.com → /chat/completions",
        note: "DeepSeek 模型价格页标注的 OpenAI Format Base URL。",
        billingNote: "按量计费；输入与输出 Token 费率分开。",
      },
      {
        provider: "anthropic",
        baseUrl: "https://api.deepseek.com/anthropic",
        status: "available",
        label: "Anthropic Messages",
        serviceLabel: "DeepSeek API",
        endpointNote: "https://api.deepseek.com/anthropic → /v1/messages",
        note: "DeepSeek 官方 Anthropic API 指南标注的 Base URL。",
        billingNote: "按量计费；Anthropic 格式中的 thinking budget 会被忽略，effort 规则以 DeepSeek 文档为准。",
      },
    ],
    referenceUrl: "https://api-docs.deepseek.com/quick_start/pricing/",
    websiteUrl: "https://platform.deepseek.com",
    apiKeyUrl: "https://platform.deepseek.com/api_keys",
    models: [
      { model: "deepseek-v4-pro", displayName: "DeepSeek V4 Pro", maxOutputTokens: 384000, maxOutputVerified: true, contextWindow: 1000000, contextWindowVerified: true, stability: "stable" },
      { model: "deepseek-v4-flash", displayName: "DeepSeek V4 Flash", maxOutputTokens: 384000, maxOutputVerified: true, contextWindow: 1000000, contextWindowVerified: true, stability: "stable" },
    ],
  },
  {
    id: "alibaba",
    name: "阿里云百炼",
    icon: "alibaba",
    category: "official",
    model: "qwen3.7-max",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    provider: "generic-chat-completion-api",
    description: "阿里云百炼官方 OpenAI-compatible API",
    protocolNote: "Droid provider=generic-chat-completion-api；调用 DashScope OpenAI-compatible Chat Completions。",
    endpointNote: "https://dashscope.aliyuncs.com/compatible-mode/v1 → /chat/completions",
    verificationNote: "qwen3.7-max 的 1M context / 64K 输出按阿里 Model Studio 文档核对；coder 型号为 rolling。",
    verificationStatus: "verified",
    maxOutputVerificationNote: "qwen3.7-max 的 64K 输出上限已按阿里 Model Studio 文档核对；qwen3-coder-plus 不自动写入。",
    contextWindowVerificationNote: "qwen3.7-max 的 1,000,000 context 已按 Model Studio 精确模型表核对。",
    billingNote: "Model Studio 按量 API；输入与输出 Token 分别计费，服务区域决定 Base URL 与可用模型。",
    protocols: [
      {
        provider: "generic-chat-completion-api",
        baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
        status: "recommended",
        label: "OpenAI Chat Completions",
        serviceLabel: "Model Studio Pay-as-you-go",
        endpointNote: "https://dashscope.aliyuncs.com/compatible-mode/v1 → /chat/completions",
        note: "阿里云百炼官方 OpenAI-compatible Chat 接口。",
        billingNote: "按量计费；请使用通用 Model Studio API Key，而不是计划专用 Key。",
      },
    ],
    referenceUrl: "https://help.aliyun.com/en/model-studio/text-generation-model/",
    websiteUrl: "https://bailian.console.aliyun.com",
    apiKeyUrl: "https://bailian.console.aliyun.com/?apiKey=1",
    models: [
      { model: "qwen3.7-max", displayName: "Qwen3.7 Max", maxOutputTokens: 65536, maxOutputVerified: true, contextWindow: 1000000, contextWindowVerified: true, stability: "stable" },
      { model: "qwen3-coder-plus", displayName: "Qwen3 Coder Plus", stability: "rolling" },
    ],
  },
  {
    id: "alibaba-coding-plan",
    name: "Alibaba Model Studio Coding Plan",
    icon: "alibaba",
    category: "plan",
    model: "qwen3.7-plus",
    baseUrl: "https://coding-intl.dashscope.aliyuncs.com/v1",
    provider: "generic-chat-completion-api",
    noImageSupport: true,
    description: "Model Studio Coding Plan 专属 Key / Endpoint；按调用次数消耗订阅配额",
    protocolNote: "Coding Plan 同时提供 OpenAI Chat Completions 与 Anthropic Messages，并区分两个官方服务域名。",
    endpointNote: "https://coding-intl.dashscope.aliyuncs.com/v1 → /chat/completions",
    verificationNote: "计划专属 Key 格式、四个 Endpoint 与按调用次数扣减规则已按 Model Studio FAQ / More Tools 核对。",
    verificationStatus: "verified",
    maxOutputVerificationNote: "只对精确模型使用其官方模型页上限；计划中的滚动模型目录不统一写死。",
    contextWindowVerificationNote: "只对精确模型使用其官方模型页上限；计划中的滚动模型目录不统一写死。",
    billingNote: "月度订阅 + 5 小时 / 周 / 月调用次数配额；不按 Token 展示用量，不会自动转为按量计费。",
    protocols: [
      {
        id: "alibaba-coding-intl-openai-chat",
        provider: "generic-chat-completion-api",
        baseUrl: "https://coding-intl.dashscope.aliyuncs.com/v1",
        status: "recommended",
        label: "OpenAI Chat Completions",
        serviceLabel: "Model Studio · coding-intl.dashscope",
        endpointNote: "https://coding-intl.dashscope.aliyuncs.com/v1 → /chat/completions",
        note: "Coding Plan 专属 OpenAI-compatible Endpoint。",
        billingNote: "按调用次数消耗订阅配额；必须使用 `sk-sp-` 计划专用 Key。",
        referenceUrl: "https://help.aliyun.com/en/model-studio/coding-plan-faq",
      },
      {
        id: "alibaba-coding-intl-anthropic",
        provider: "anthropic",
        baseUrl: "https://coding-intl.dashscope.aliyuncs.com/apps/anthropic",
        status: "available",
        label: "Anthropic Messages",
        serviceLabel: "Model Studio · coding-intl.dashscope",
        endpointNote: "https://coding-intl.dashscope.aliyuncs.com/apps/anthropic → /v1/messages",
        note: "Coding Plan 专属 Anthropic-compatible Endpoint。",
        billingNote: "按调用次数消耗订阅配额；必须使用 `sk-sp-` 计划专用 Key。",
        referenceUrl: "https://help.aliyun.com/en/model-studio/coding-plan-faq",
      },
      {
        id: "alibaba-coding-dashscope-openai-chat",
        provider: "generic-chat-completion-api",
        baseUrl: "https://coding.dashscope.aliyuncs.com/v1",
        status: "available",
        label: "OpenAI Chat Completions",
        serviceLabel: "Model Studio · coding.dashscope",
        endpointNote: "https://coding.dashscope.aliyuncs.com/v1 → /chat/completions",
        note: "Coding Plan 专属 OpenAI-compatible Endpoint。请使用同一服务签发的计划 Key。",
        billingNote: "按调用次数消耗订阅配额；普通 Model Studio Key 不适用。",
        referenceUrl: "https://help.aliyun.com/zh/model-studio/more-tools",
      },
      {
        id: "alibaba-coding-dashscope-anthropic",
        provider: "anthropic",
        baseUrl: "https://coding.dashscope.aliyuncs.com/apps/anthropic",
        status: "available",
        label: "Anthropic Messages",
        serviceLabel: "Model Studio · coding.dashscope",
        endpointNote: "https://coding.dashscope.aliyuncs.com/apps/anthropic → /v1/messages",
        note: "Coding Plan 专属 Anthropic-compatible Endpoint。请使用同一服务签发的计划 Key。",
        billingNote: "按调用次数消耗订阅配额；普通 Model Studio Key 不适用。",
        referenceUrl: "https://help.aliyun.com/zh/model-studio/more-tools",
      },
    ],
    referenceUrl: "https://help.aliyun.com/en/model-studio/coding-plan-faq",
    websiteUrl: "https://bailian.console.aliyun.com",
    apiKeyUrl: "https://bailian.console.aliyun.com",
    models: [
      { model: "qwen3.7-plus", displayName: "Qwen3.7 Plus", maxOutputTokens: 65536, maxOutputVerified: true, contextWindow: 1000000, contextWindowVerified: true, stability: "stable" },
      { model: "qwen3.6-plus", displayName: "Qwen3.6 Plus", maxOutputTokens: 65536, maxOutputVerified: true, contextWindow: 1000000, contextWindowVerified: true, stability: "stable" },
    ],
  },
  {
    id: "alibaba-token-plan-team",
    name: "Alibaba Model Studio Token Plan Team",
    icon: "alibaba",
    category: "plan",
    model: "qwen3.7-plus",
    baseUrl: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
    provider: "generic-chat-completion-api",
    noImageSupport: true,
    description: "Token Plan Team 专属 API Key / Endpoint；与 Coding Plan 和按量 API 分开",
    protocolNote: "Token Plan Team 官方提供 OpenAI Chat Completions 与 Anthropic Messages 两种协议。",
    endpointNote: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1 → /chat/completions",
    verificationNote: "Endpoint 与专用 Key 来源已按 2026-06 Token Plan Team Quick Start 核对；支持模型目录动态更新。",
    verificationStatus: "dynamic",
    maxOutputVerificationNote: "按实际选择的精确模型核验，不对整个 Token Plan 写统一上限。",
    contextWindowVerificationNote: "按实际选择的精确模型核验，不对整个 Token Plan 写统一上限。",
    billingNote: "团队席位 / Token Plan 额度；API Key 与 Coding Plan、按量 API Key 不互通。",
    protocols: [
      {
        id: "alibaba-token-plan-openai-chat",
        provider: "generic-chat-completion-api",
        baseUrl: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        status: "recommended",
        label: "OpenAI Chat Completions",
        serviceLabel: "Model Studio Token Plan Team",
        endpointNote: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1 → /chat/completions",
        note: "Token Plan Team 专属 OpenAI-compatible Endpoint。",
        billingNote: "团队 Token Plan 额度；必须使用成员专属 Token Plan Key。",
        referenceUrl: "https://help.aliyun.com/en/model-studio/token-plan-quickstart",
      },
      {
        id: "alibaba-token-plan-anthropic",
        provider: "anthropic",
        baseUrl: "https://token-plan.cn-beijing.maas.aliyuncs.com/apps/anthropic",
        status: "available",
        label: "Anthropic Messages",
        serviceLabel: "Model Studio Token Plan Team",
        endpointNote: "https://token-plan.cn-beijing.maas.aliyuncs.com/apps/anthropic → /v1/messages",
        note: "Token Plan Team 专属 Anthropic-compatible Endpoint。",
        billingNote: "团队 Token Plan 额度；必须使用成员专属 Token Plan Key。",
        referenceUrl: "https://help.aliyun.com/en/model-studio/token-plan-quickstart",
      },
    ],
    referenceUrl: "https://help.aliyun.com/en/model-studio/token-plan-quickstart",
    websiteUrl: "https://bailian.console.aliyun.com",
    apiKeyUrl: "https://bailian.console.aliyun.com",
    models: [
      { model: "qwen3.7-plus", displayName: "Qwen3.7 Plus", maxOutputTokens: 65536, maxOutputVerified: true, contextWindow: 1000000, contextWindowVerified: true, stability: "rolling" },
    ],
  },
  {
    id: "opencode-go-openai-compatible",
    name: "OpenCode Go（OpenAI 兼容）",
    icon: "opencode",
    category: "plan",
    model: "kimi-k2.7-code",
    baseUrl: "https://opencode.ai/zen/go/v1",
    provider: "generic-chat-completion-api",
    noImageSupport: true,
    description: "OpenCode Go 订阅套餐；GLM / Kimi / DeepSeek / MiMo 走 OpenAI-compatible Chat Completions",
    protocolNote: "Droid provider=generic-chat-completion-api；Go 文档端点为 /chat/completions。注意：OpenCode TUI 内部可使用 opencode-go/<model-id>，但 Droid BYOK 发送到 raw API 时使用下方模型原始 ID。",
    endpointNote: "https://opencode.ai/zen/go/v1 → /chat/completions",
    verificationNote: "模型 ID、Endpoint 与 AI SDK 包已按 OpenCode Go 官方中文文档 API 端点表核验（页面最近更新 2026-06-30）；只收录端点表中明确标注为 @ai-sdk/openai-compatible 的模型。",
    verificationStatus: "verified",
    maxOutputVerificationNote: "OpenCode Go 官方端点表未公布每个模型的最大输出 Token；本预设不写固定 maxOutputTokens，避免把模型能力误降级。需要上限时请以 OpenCode /models 元数据或供应商当前说明再核验。",
    contextWindowVerificationNote: "OpenCode Go 官方端点表未公布上下文窗口；本预设不写固定 maxContextLimit，默认交由 Droid/供应商处理。",
    billingNote: "OpenCode Go 订阅额度按美元价值计量；官方说明包含 5 小时、每周、每月额度及按模型的预估请求数。",
    protocols: [
      {
        id: "opencode-go-openai-chat",
        provider: "generic-chat-completion-api",
        baseUrl: "https://opencode.ai/zen/go/v1",
        status: "recommended",
        label: "OpenAI-compatible Chat Completions",
        serviceLabel: "OpenCode Go",
        endpointNote: "https://opencode.ai/zen/go/v1 → /chat/completions",
        note: "官方端点表中 GLM / Kimi / DeepSeek / MiMo 使用 @ai-sdk/openai-compatible。",
        billingNote: "Go 订阅额度；API Key 在 OpenCode Zen/Go 控制台获取。",
        referenceUrl: "https://opencode.ai/docs/zh-cn/go/",
      },
    ],
    referenceUrl: "https://opencode.ai/docs/zh-cn/go/",
    websiteUrl: "https://opencode.ai/docs/zh-cn/go/",
    apiKeyUrl: "https://opencode.ai/auth",
    models: [
      { model: "glm-5.2", displayName: "GLM-5.2 [OpenCode Go]", stability: "stable" },
      { model: "glm-5.1", displayName: "GLM-5.1 [OpenCode Go]", stability: "stable" },
      { model: "kimi-k2.7-code", displayName: "Kimi K2.7 Code [OpenCode Go]", stability: "stable" },
      { model: "kimi-k2.6", displayName: "Kimi K2.6 [OpenCode Go]", stability: "stable" },
      { model: "deepseek-v4-pro", displayName: "DeepSeek V4 Pro [OpenCode Go]", stability: "stable" },
      { model: "deepseek-v4-flash", displayName: "DeepSeek V4 Flash [OpenCode Go]", stability: "stable" },
      { model: "mimo-v2.5", displayName: "MiMo-V2.5 [OpenCode Go]", stability: "stable" },
      { model: "mimo-v2.5-pro", displayName: "MiMo-V2.5-Pro [OpenCode Go]", stability: "stable" },
    ],
  },
  {
    id: "opencode-go-anthropic-compatible",
    name: "OpenCode Go（Anthropic 兼容）",
    icon: "opencode",
    category: "plan",
    model: "qwen3.7-max",
    baseUrl: "https://opencode.ai/zen/go/v1",
    provider: "anthropic",
    noImageSupport: true,
    description: "OpenCode Go 订阅套餐；MiniMax / Qwen 走 Anthropic-compatible Messages",
    protocolNote: "Droid provider=anthropic；Go 文档端点为 /messages，Droid 会从 Base URL 自动调用 /messages。注意：OpenCode TUI 内部可使用 opencode-go/<model-id>，Droid BYOK raw API 使用下方模型原始 ID。",
    endpointNote: "https://opencode.ai/zen/go/v1 → /messages",
    verificationNote: "模型 ID、Endpoint 与 AI SDK 包已按 OpenCode Go 官方中文文档 API 端点表核验（页面最近更新 2026-06-30）；只收录端点表中明确标注为 @ai-sdk/anthropic 的模型。",
    verificationStatus: "verified",
    maxOutputVerificationNote: "OpenCode Go 官方端点表未公布每个模型的最大输出 Token；本预设不写固定 maxOutputTokens，避免把模型能力误降级。需要上限时请以 OpenCode /models 元数据或供应商当前说明再核验。",
    contextWindowVerificationNote: "OpenCode Go 官方端点表未公布上下文窗口；本预设不写固定 maxContextLimit，默认交由 Droid/供应商处理。",
    billingNote: "OpenCode Go 订阅额度按美元价值计量；官方说明包含 5 小时、每周、每月额度及按模型的预估请求数。",
    protocols: [
      {
        id: "opencode-go-anthropic-messages",
        provider: "anthropic",
        baseUrl: "https://opencode.ai/zen/go/v1",
        status: "recommended",
        label: "Anthropic-compatible Messages",
        serviceLabel: "OpenCode Go",
        endpointNote: "https://opencode.ai/zen/go/v1 → /messages",
        note: "官方端点表中 MiniMax / Qwen 使用 @ai-sdk/anthropic。",
        billingNote: "Go 订阅额度；API Key 在 OpenCode Zen/Go 控制台获取。",
        referenceUrl: "https://opencode.ai/docs/zh-cn/go/",
      },
    ],
    referenceUrl: "https://opencode.ai/docs/zh-cn/go/",
    websiteUrl: "https://opencode.ai/docs/zh-cn/go/",
    apiKeyUrl: "https://opencode.ai/auth",
    models: [
      { model: "minimax-m3", displayName: "MiniMax M3 [OpenCode Go]", stability: "stable" },
      { model: "minimax-m2.7", displayName: "MiniMax M2.7 [OpenCode Go]", stability: "stable" },
      { model: "minimax-m2.5", displayName: "MiniMax M2.5 [OpenCode Go]", stability: "legacy" },
      { model: "qwen3.7-max", displayName: "Qwen3.7 Max [OpenCode Go]", stability: "stable" },
      { model: "qwen3.7-plus", displayName: "Qwen3.7 Plus [OpenCode Go]", stability: "stable" },
      { model: "qwen3.6-plus", displayName: "Qwen3.6 Plus [OpenCode Go]", stability: "stable" },
    ],
  },
  {
    id: "opencode-zen",
    name: "OpenCode Zen（OpenAI）",
    icon: "opencode",
    category: "gateway",
    model: "gpt-5.5",
    baseUrl: "https://opencode.ai/zen/v1",
    provider: "openai",
    description: "OpenCode 官方模型网关；OpenAI-family 走 Responses API，不代表原厂直连",
    protocolNote: "Droid provider=openai；仅适用于 OpenCode Zen 文档中 endpoint 为 /responses 的模型。",
    endpointNote: "https://opencode.ai/zen/v1 → /responses",
    verificationNote: "协议/endpoint 按 OpenCode Zen 官方端点表核对；模型目录会变化，可用 /models 或 OpenCode 文档复核。",
    verificationStatus: "partial",
    maxOutputVerificationNote: "OpenCode Zen 模型目录动态变化，本预设不写固定最大输出。",
    contextWindowVerificationNote: "OpenCode Zen 由网关公布模型元数据；不直接套用原厂上限，建议通过 `/v1/models` 获取。",
    billingNote: "OpenCode Zen 网关余额 / Credits；具体输入输出费率以 Zen 当前模型目录为准。",
    protocols: [
      {
        provider: "openai",
        baseUrl: "https://opencode.ai/zen/v1",
        status: "recommended",
        label: "OpenAI Responses",
        serviceLabel: "OpenCode Zen Gateway",
        endpointNote: "https://opencode.ai/zen/v1 → /responses",
        note: "OpenCode Zen 端点表中 GPT family 使用 /responses。",
        billingNote: "网关 Credits；模型费率动态更新。",
      },
    ],
    referenceUrl: "https://opencode.ai/docs/zen",
    websiteUrl: "https://opencode.ai/docs/zen",
    apiKeyUrl: "https://opencode.ai/auth",
    models: [
      { model: "gpt-5.5", displayName: "GPT 5.5", stability: "stable" },
      { model: "gpt-5.5-pro", displayName: "GPT 5.5 Pro", stability: "stable" },
      { model: "gpt-5.4", displayName: "GPT 5.4", stability: "stable" },
      { model: "gpt-5.4-pro", displayName: "GPT 5.4 Pro", stability: "stable" },
      { model: "gpt-5.4-mini", displayName: "GPT 5.4 Mini", stability: "stable" },
      { model: "gpt-5.4-nano", displayName: "GPT 5.4 Nano", stability: "stable" },
    ],
  },
  {
    id: "opencode-zen-anthropic",
    name: "OpenCode Zen（Claude）",
    icon: "opencode",
    category: "gateway",
    model: "claude-opus-4-8",
    baseUrl: "https://opencode.ai/zen",
    provider: "anthropic",
    description: "OpenCode 官方模型网关；Claude-family 走 Anthropic Messages API，不代表原厂直连",
    protocolNote: "Droid provider=anthropic；仅适用于 OpenCode Zen 文档中 endpoint 为 /messages 的模型。",
    endpointNote: "https://opencode.ai/zen → /v1/messages",
    verificationNote: "协议/endpoint 按 OpenCode Zen 官方端点表核对；模型目录会变化，可用 OpenCode 文档复核。",
    verificationStatus: "partial",
    maxOutputVerificationNote: "OpenCode Zen Claude family 模型目录动态变化，本预设不写固定最大输出。",
    contextWindowVerificationNote: "OpenCode Zen 由网关公布模型元数据；不直接套用原厂上限，建议通过 `/v1/models` 获取。",
    billingNote: "OpenCode Zen 网关余额 / Credits；具体输入输出费率以 Zen 当前模型目录为准。",
    protocols: [
      {
        provider: "anthropic",
        baseUrl: "https://opencode.ai/zen",
        status: "recommended",
        label: "Anthropic Messages",
        serviceLabel: "OpenCode Zen Gateway",
        endpointNote: "https://opencode.ai/zen → /v1/messages",
        note: "OpenCode Zen 端点表中 Claude family 使用 /zen/v1/messages。",
        billingNote: "网关 Credits；模型费率动态更新。",
      },
    ],
    referenceUrl: "https://opencode.ai/docs/zen",
    websiteUrl: "https://opencode.ai/docs/zen",
    apiKeyUrl: "https://opencode.ai/auth",
    models: [
      { model: "claude-opus-4-8", displayName: "Claude Opus 4.8", stability: "stable" },
      { model: "claude-opus-4-7", displayName: "Claude Opus 4.7", stability: "stable" },
      { model: "claude-opus-4-6", displayName: "Claude Opus 4.6", stability: "stable" },
      { model: "claude-sonnet-4-6", displayName: "Claude Sonnet 4.6", stability: "stable" },
    ],
  },
];
